# Generated by Django 4.1 on 2022-08-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_account_alter_post_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='NewAccount',
        ),
    ]
